## Chap3 - Linear regression

In [1]:
import torch
X = torch.Tensor(2, 3)

In [2]:
print(X)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
X = torch.Tensor([[1,2,3], [4,5,6]])

In [4]:
print(X)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 기울기를 계산하는 코드

In [5]:
x = torch.tensor(data = [2.0, 3.0], requires_grad = True)
y = x**2
z = 2*y + 3

In [6]:
target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs(z-target))
loss.backward()

In [7]:
print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


<ipython-input-7-6c1d48845c75>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x.grad, y.grad, z.grad)


## 선형회귀 분석모델

In [8]:
import torch #torch 라이브러리 불러옴
import torch.nn as nn # torch의 신경망 모델들을 불러옴
import torch.optim as optim # torch의 경사하강법 알고리즘을 불러옴
import torch.nn.init as init # 텐서에 초기값을 주기 위해 필요한 함수들이 있음.

In [9]:
num_data = 1000
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data, 1),-10,10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2 * x + 3
y_noise = y + noise

In [10]:
model = nn.Linear(1,1)
loss_func = nn.L1Loss()

In [11]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [12]:
label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i%10 == 0:
        print(loss.data)
        param_list = list(model.parameters())
        print(param_list[0].item(), param_list[1].item())

tensor(12.1431)
-0.3401641845703125 0.37364789843559265
tensor(9.6793)
0.15580324828624725 0.38508787751197815
tensor(7.2702)
0.6455875635147095 0.40034788846969604
tensor(5.0098)
1.1186367273330688 0.4227278530597687
tensor(3.1898)
1.5345605611801147 0.4611278474330902
tensor(2.5226)
1.7587873935699463 0.5308078527450562
tensor(2.3744)
1.833625078201294 0.6199279427528381
tensor(2.2689)
1.8749167919158936 0.7133678793907166
tensor(2.1697)
1.9062597751617432 0.8076677322387695
tensor(2.0756)
1.9252406358718872 0.9025877118110657
tensor(1.9841)
1.9398618936538696 0.9970276355743408
tensor(1.8956)
1.9486486911773682 1.0905076265335083
tensor(1.8111)
1.9545221328735352 1.182127594947815
tensor(1.7285)
1.963297963142395 1.2724676132202148
tensor(1.6494)
1.970413088798523 1.3609676361083984
tensor(1.5730)
1.976675271987915 1.4480277299880981
tensor(1.5008)
1.9786310195922852 1.532767653465271
tensor(1.4331)
1.9795531034469604 1.6147676706314087
tensor(1.3698)
1.980455756187439 1.69416773319